///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Getlogin {
/*
{
  "login_user": "sttest",
  "login_password": "sttest",
  "login_name": "สมชาย ลองล็อกอิน",
  "login_personnal": "ST100593",
  "login_profile": "https://strubberdata.com/4.HRM/personnel_img/ST100103/S__14565382.jpg"
}
*/

  String? loginUser;
  String? loginPassword;
  String? loginName;
  String? loginPersonnal;
  String? loginProfile;

  Getlogin({
    this.loginUser,
    this.loginPassword,
    this.loginName,
    this.loginPersonnal,
    this.loginProfile,
  });
  Getlogin.fromJson(Map<String, dynamic> json) {
    loginUser = json['login_user']?.toString();
    loginPassword = json['login_password']?.toString();
    loginName = json['login_name']?.toString();
    loginPersonnal = json['login_personnal']?.toString();
    loginProfile = json['login_profile']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['login_user'] = loginUser;
    data['login_password'] = loginPassword;
    data['login_name'] = loginName;
    data['login_personnal'] = loginPersonnal;
    data['login_profile'] = loginProfile;
    return data;
  }
}

class LoginModel {
  bool? success;
  String? message;
  Getlogin? data;

  LoginModel({
    this.success,
    this.message,
    this.data
  });

  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? Getlogin.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}

/*
// กำหนดฟิลด์ข้อมูลของตาราง
class LoginFields {
  // สร้างเป็นลิสรายการสำหรับคอลัมน์ฟิลด์
  static final List<String> values = [
    id, username, password, name, token, lastlogin, active
  ];

  // กำหนดแต่ละฟิลด์ของตาราง ต้องเป็น String ทั้งหมด
  static final String id = 'login_id';
  static final String username = 'login_user';
  static final String password = 'login_password';
  static final String name = 'login_name';
  static final String token = 'login_token';
  static final String lastlogin = 'login_lastlogin';
  static final String active = 'login_active';
}


// ส่วนของ Data Model
class Login {
  final int id;
  final String username;
  final String password;
  final String? name;
  final String? token;
  final DateTime? lastlogin;
  final bool? active;

  // constructor
  const Login({
    required this.id,
    required this.username,
    required this.password,
    this.name,
    this.token,
    this.lastlogin,
    this.active,
  });

  // สำหรับแปลงข้อมูลจาก Json เป็น  object
  static Login fromJson(Map<String, Object?> json) =>
      Login(
        id: json[LoginFields.id] as int,
        username: json[LoginFields.username] as String,
        password: json[LoginFields.password] as String,
        name: json[LoginFields.name] as String,
        token: json[LoginFields.token] as String,
        lastlogin: DateTime.parse(json[LoginFields.lastlogin] as String),
        active: json[LoginFields.active] == 1,
      );

  // สำหรับแปลง  object เป็น Json
  Map<String, Object?> toJson() => {
    LoginFields.id: id,
    LoginFields.username: username,
    LoginFields.password: password,
    LoginFields.name: name,
    LoginFields.token: token,
    LoginFields.lastlogin: lastlogin?.toIso8601String() ?? "",
    LoginFields.active: active!=null ? 1 : 0,
  };

}

 */